# For SCSS-Lint v0.32.0

linters:
  # "value !important;" not "value!important ;"
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
    severity: error

  BemDepth:
    enabled: true
    max_elements: 1

  # "border: 0" not "border: none"
  BorderZero:
    enabled: true
    severity: error
    convention: zero

  # ChainedClasses:
  #   enabled: false

  # "#00ff00" not "green"
  # (AB: Causes problems with o-colors < 3, because o-colors uses
  # color names that are also valid CSS color strings)
  ColorKeyword:
    enabled: false

  # // not /**/
  Comment:
    enabled: true
    style: silent
    severity: error

  # Disallow "@debug"
  DebugStatement:
    enabled: true

  # @extend must come first, then properties, then nested rulesets
  DeclarationOrder:
    # this has been disabled because to my knowlege
    # there's no way to specify mixins to ignore the order of
    enabled: false

  # must explain why you don't need this linter setting
  DisableLinterReason:
    enabled: true

  # Warn when the same property appears more than once in the same ruleset
  # This is not a deal breaker, as authors may repeat properties
  # in the case where both a value and its fallback are needed
  DuplicateProperty:
    enabled: true

  # "} else {" not "}\n else {"
  ElsePlacement:
    enabled: true
    style: same_line

  # Require an empty line between rulesets
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  # Disallow empty rulesets
  EmptyRule:
    enabled: true

  # ExtendDirective:
  #   enabled: false

  # Require a newline at the end of the file
  FinalNewline:
    enabled: true
    present: true

  # #aabbcc good, #abc bad. Makes the codebase more searchable
  HexLength:
    enabled: true
    style: long
    severity: error

  # Require hex colors to be lowercase (if they include any of the letters a-f)
  HexNotation:
    enabled: true
    style: lowercase

  # Hex colors must be actual colors (ie not #ab or #00mm00)
  HexValidation:
    enabled: true

  # Disallow using ID Selectors
  IdSelector:
    enabled: true

   # Avoid using !important
  ImportantRule:
    enabled: true

  # "@import 'path/to/partial'" not "@import 'path/to/_partial.scss'"
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
    severity: error

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 2
    severity: error

  # 0.1 not .1
  LeadingZero:
    enabled: true
    style: include_zero
    severity: error

  # Disallow more than one ruleset with the same selector in the same file
  MergeableSelector:
    enabled: false
    force_nesting: false

  # forbid non-alphanumeric characters
  # in mixin, variable and function names.
  NameFormat:
    enabled: true
    convention: '^(?:[a-z_][a-z0-9_\-]+|[abcdeixyz]+|-webkit-image-set)$'
    severity: error

  # Thou shall nest 3 levels deep maximum. Not 4, nor 5.
  # See SelectorDepth for control over the actually maximum authorized depth
  NestingDepth:
    enabled: true
    max_depth: 4
    # ignore_parent_selectors: false

  # @extend %placeholders, don't @extend .a-class
  PlaceholderInExtend:
    enabled: true
    severity: error

   # Allow any number of properties in a ruleset
  PropertyCount:
    enabled: false

  # Require properties to be in alphabetical order
  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
    order:
      - align-content
      - align-items
      - align-self
      - all
      - animation
      - appearance
      - backface-visibility
      - background
      - background-attachment
      - background-blend-mode
      - background-clip
      - background-color
      - background-image
      - background-origin
      - background-position
      - background-position-x
      - background-position-y
      - background-repeat
      - background-repeat-x
      - background-repeat-y
      - background-size
      - border
      - border-bottom
      - border-bottom-color
      - border-bottom-left-radius
      - border-bottom-right-radius
      - border-bottom-style
      - border-bottom-width
      - border-collapse
      - border-color
      - border-image
      - border-image
      - border-image-outset
      - border-image-repeat
      - border-image-slice
      - border-image-source
      - border-image-width
      - border-left
      - border-left-color
      - border-left-style
      - border-left-width
      - border-radius
      - border-right
      - border-right-color
      - border-right-style
      - border-right-width
      - border-spacing
      - border-style
      - border-top
      - border-top-color
      - border-top-left-radius
      - border-top-right-radius
      - border-top-style
      - border-top-width
      - border-width
      - bottom
      - box-decoration-break
      - box-shadow
      - box-sizing
      - break-inside
      - clear
      - clip
      - clip-path
      - color
      - column-count
      - column-fill
      - column-gap
      - column-rule
      - column-span
      - column-width
      - columns
      - content
      - counter-increment
      - counter-reset
      - cursor
      - direction
      - display
      - filter
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - float
      - font
      - font-family
      - font-feature-settings
      - font-size
      - font-size-adjust
      - font-stretch
      - font-style
      - font-variant
      - font-weight
      - grid-column
      - grid-column-align
      - grid-column-span
      - grid-columns
      - grid-row
      - grid-row-align
      - grid-row-span
      - grid-rows
      - hanging-punctuation
      - height
      - hyphens
      - image-rendering
      - isolation
      - justify-content
      - left
      - letter-spacing
      - line-height
      - list-style
      - margin
      - margin-bottom
      - margin-left
      - margin-right
      - margin-top
      - max-height
      - max-width
      - min-height
      - min-width
      - mix-blend-mode
      - object-fit
      - object-position
      - opacity
      - order
      - orphans
      - outline
      - overflow
      - overflow-x
      - overflow-y
      - padding
      - padding-bottom
      - padding-left
      - padding-right
      - padding-top
      - page-break
      - perspective
      - perspective-origin
      - pointer-events
      - position
      - quotes
      - resize
      - right
      - scrollbar
      - shape-outside
      - tab-size
      - text-align
      - text-align-last
      - text-decoration
      - text-decoration-color
      - text-decoration-line
      - text-decoration-skip
      - text-decoration-style
      - text-indent
      - text-overflow
      - text-rendering
      - text-shadow
      - text-stroke
      - text-transform
      - text-underline-position
      - top
      - transform
      - transform-origin
      - transform-style
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function
      - unicode-bidi
      - user-select
      - vertical-align
      - visibility
      - white-space
      - widows
      - width
      - will-change
      - word-break
      - word-spacing
      - z-index
      - zoom

  # Disallow unknown CSS property names
  PropertySpelling:
    enabled: true
    extra_properties:
      - text-size-adjust
    disabled_properties: []

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  PseudoElement:
    enabled: false

  # ".class, [foo]" not "span.class, div[foo]"
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false
    severity: error

  # Limit selector depth
  # We decided to deal with this via peer review in
  # https://github.com/Financial-Times/ft-origami/issues/243
  SelectorDepth:
    enabled: true
    max_depth: 3

  # SelectorFormat:
  #   enabled: true
  #   convention: hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern
  # SelectorFormat:
  #   enabled: true
  #   convention: hyphenated_BEM
  #   class_convention: '^(?:u|is|has)\-[a-z][a-zA-Z0-9]*$|^(?!u|is|has)[a-zA-Z][a-zA-Z0-9]*(?:\-[a-z][a-zA-Z0-9]*)?(?:\-\-[a-z][a-zA-Z0-9]*)?$'

  # Allow lowercase only, but forbid non-alphanumeric characters
  # in selector names.
  SelectorFormat:
    enabled: true
    convention: '^[a-z0-9_\-]+$'
    severity: error

  # margin: 1px not margin: 1px 1px 1px 1px;
  Shorthand:
    enabled: true
    severity: error

  # Disallow properties on the same line "margin: 0; padding: 0;"
  SingleLinePerProperty:
    enabled: true
    # enable simple rules to be on a single line "el { margin: 0; }"
    allow_single_line_rule_sets: true
    severity: error

  SingleLinePerSelector:
    enabled: false

  # rgb(0, 0, 0) not rgb(0,0,0)
  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'
    severity: error

  # margin: 0px not margin:0px
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
    severity: error

  # margin: 0px not margin : 0px
  # (note clearly this should be called NoSpaceAfterPropertyName)
  SpaceAfterPropertyName:
    enabled: true
    severity: error

  SpaceAfterVariableName:
    enabled: true

  # 1px + 10px not 1px+10px
  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'at_least_one_space', or 'no_space'

  # .thing { not .thing{
  SpaceBeforeBrace:
    enabled: true
    style: space
    # allow_single_line_padding: true
    allow_single_line_padding: false
    severity: error

  # rgb(0, 0, 0) not rgb( 0, 0, 0 )
  SpaceBetweenParens:
    enabled: false
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  # Every property value must end with a semicolon
  TrailingSemicolon:
    enabled: true
    severity: error

  # TrailingWhitespace:
  #   enabled: true

  # "margin: .5em;" not "margin: .500em;"
  TrailingZero:
    enabled: true

  # TransitionAll:
  #   enabled: false

  # No unnecessary fractions: 1 not 1.0
  UnnecessaryMantissa:
    enabled: true
    severity: error

  # Disable this rule to allow parent references such as "& + * {}"
  UnnecessaryParentReference:
    enabled: false

  UrlFormat:
    enabled: false

  # url("example.com") not url(example.com)
  UrlQuotes:
    enabled: true

  # Allow any property to have literal values
  VariableForProperty:
    enabled: false

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: [
      'tap-highlight-color',
      'touch-callout',
      'touch-select'
    ]
    severity: warning


  # No units on zero values: 0 not 0px
  ZeroUnit:
    enabled: false